services:
  db:
    image: mysql:latest
    container_name: nutricalc_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: engsoft
      MYSQL_DATABASE: nutricalc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
