services:
  web: # serviço do servidor web
    container_name: nutricalc_web
    build: .  # Constroi o Dockerfile
    ports:
      - "80:80" # porta para acesso: 80 (HTTP)
    volumes:
      - .:/var/www/html #
    depends_on: # Espera o banco de dados iniciar
      - db
  db: # serviço do banco de dados
    image: mysql:latest 
    container_name: nutricalc_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: engsoft
      MYSQL_DATABASE: nutricalc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: